/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_icmp4j_platform_unix_jni_Icmp4jJNI */

#ifndef _Included_org_icmp4j_platform_unix_jni_Icmp4jJNI
#define _Included_org_icmp4j_platform_unix_jni_Icmp4jJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_icmp4j_platform_unix_jni_Icmp4jJNI
 * Method:    icmp_start
 * Signature: ()J
 */
JNIEXPORT void JNICALL Java_org_icmp4j_platform_unix_jni_Icmp4jJNI_icmp_1start
  (JNIEnv *, jobject);

/*
 * Class:     org_icmp4j_platform_unix_jni_Icmp4jJNI
 * Method:    icmp_test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_icmp4j_platform_unix_jni_Icmp4jJNI_icmp_1test
  (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
